[tool.poetry]
name = "swervelib"
version = "0.2.0"
description = "Swerve drive library for FRC"
authors = ["Ethan Wall <ewall25@jesuittampa.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.11"
robotpy = {version = "^2023.2.1", extras = ["ctre", "commands2", "rev", "photonvision"]}
robotpy-apriltag = "^2023.2.1.1"
Pint = "^0.20.1"

[tool.poetry.group.dev.dependencies]
mypy = "^0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
